import {TimezoneDate} from './timezone-date.model';
import {Stop} from './stop.model';

export class Timetable {
    constructor(
        public id: number,
        public timetableId: number,
        public carrierId: number,
        public isorId: number,
        public trId: string,
        public trNumber: number,
        public category: string,
        public operator: string,
        public lineId: number,
        public serviceId: number,
        public paIdent: string,
        public paVariant: string,
        public start: string,
        public end: string,
        public stationFrom: string,
        public stationFromId: string,
        public stationTo: string,
        public stationToId: string,
        public validSince: string,
        public validTill: string,
        public priority: number,
        public serviceVariantId: number,
        public routeId: number,
        public operatingId: number,
        public since: TimezoneDate,
        public till: TimezoneDate,
        public line: string,
        public name: string,
        public displayFrontText: string,
        public displaySideText: string,
        public displaySideStops: string,
        public relation: string,
        public audio: string,
        public stationIdFrom: number,
        public stationIdTo: number,
        public direction: string,
        public restriction: string,
        public length: number,
        public jikord: string,
        public poved: string,
        public isorLock: string,
        public exportTo: string,
        public usedSince: TimezoneDate,
        public usedTill: TimezoneDate,
        public weekday: string,
        public weekdayInt: number,
        public variantId: number,
        public variantPeriod: number,
        public isor: string,
        public stops: Stop[]
    ) {}
}
